# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: adopt
        java-version: 21
    - name: Cache
      uses: actions/cache@v4.3.0
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: ~/.gradle/caches/modules-2
        # An explicit key for restoring and saving the cache
        key: gradle-build-${{ hashFiles('build.gradle.kts') }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: |
          gradle-build-${{ hashFiles('build.gradle.kts') }}
          gradle-build
          gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
